### ISSUE TITLE
NJXMLParser not attributed to author or original source

### ISSUE THREAD

**Issue by a2** [NeoSmartpen/IOS-SDK2.0#7]
The files [NJXMLParser.h](https://github.com/NeoSmartpen/IOSSDK2.0/blob/6e735bacf22fa8dbe59c35172238d2d3c5d9b977/iOSSDK2.0_NISDK/NISDK/n2base/utils/NJXMLParser.h) and [NJXMLParser.m ](https://github.com/NeoSmartpen/IOSSDK2.0/blob/6e735bacf22fa8dbe59c35172238d2d3c5d9b977/iOSSDK2.0_NISDK/NISDK/n2base/utils/NJXMLParser.m) are not attributed to their author, Nick Lockwood, or original source, [nicklockwood/XMLDictionary](https://github.com/nicklockwood/XMLDictionary).

**Comment by louisjrpark** [comment]
Thank you for letting us know. The files were attributed to their author. 
Sorry for the late response.

Thanks

Best regards,
Louis Park
